language: perl6

perl6:
    - '2018.12'
    - '2020.01'
    - '2020.05.1'
    - '2020.10'
    - latest

install:
    - rakudobrew build-zef
    # Explicitly install HEAD of Cro::Core
    - zef install https://github.com/croservices/cro-core/archive/master.zip
    - zef --debug --deps-only install .
